[[http]]
# Name of the HTTP server, used for display purposes only.
name = "gem-inlfuxdb-relay-http"

# TCP address to bind to, for HTTP server.
bind-addr = "0.0.0.0:8086"

# Enable HTTPS requests.
# ssl-combined-pem = "/etc/ssl/influxdb-relay.pem"

# Array of InfluxDB instances to use as backends for Relay.
output = [
    { name="influxdb-1", location="http-output-1", timeout="10s" },
    { name="influxdb-2", location="http-output-2", timeout="10s" }
]

[[udp]]
# Name of the UDP server, used for display purposes only.
name = "gem-inlfuxdb-relay-udp"

# UDP address to bind to.
bind-addr = "0.0.0.0:8086"

# Socket buffer size for incoming connections.
read-buffer = 0 # default

# Precision to use for timestamps
precision = "n" # Can be n, u, ms, s, m, h

# Array of InfluxDB instances to use as backends for Relay.
output = [
    { name="influxdb-1", location="udp-output-1", mtu=512 },
    { name="influxdb-2", location="udp-output-2", mtu=512 }
]